#!/usr/bin/env python3
"""
Fetch fundamental data from Alpha Vantage for securities in trade logs.

This script fetches point-in-time fundamental data for each security and
saves it to separate CSV files that can be merged with the fundamental
features generated by the backtest analyzer.

Usage:
    # Basic usage - fetch for all securities in trade logs
    python run_fundamental_data_fetch.py logs/AlphaTrendStrategy

    # With custom date range
    python run_fundamental_data_fetch.py logs/AlphaTrendStrategy --start-year 2015 --end-year 2024

    # With custom output directory
    python run_fundamental_data_fetch.py logs/AlphaTrendStrategy -o analysis_output/fundamentals

    # With custom config file
    python run_fundamental_data_fetch.py logs/AlphaTrendStrategy --config my_config.json

    # Create sample config file
    python run_fundamental_data_fetch.py --create-config

Prerequisites:
    1. Create alpha_vantage_config.json with your API key
    2. Run with: python run_fundamental_data_fetch.py --create-config
    3. Edit the config file with your API key
"""

import argparse
import logging
import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from Classes.Analysis.backtest_analyzer.alpha_vantage_config import (
    AlphaVantageConfig,
    create_sample_config,
)
from Classes.Analysis.backtest_analyzer.alpha_vantage_client import AlphaVantageClient
from Classes.Analysis.backtest_analyzer.interactive_handler import InteractiveHandler
from Classes.Analysis.backtest_analyzer.fundamental_data_fetcher import FundamentalDataFetcher


def setup_logging(verbose: bool = False, log_dir: Path = None):
    """Setup logging configuration."""
    level = logging.DEBUG if verbose else logging.INFO

    handlers = [logging.StreamHandler()]

    if log_dir:
        log_dir.mkdir(parents=True, exist_ok=True)
        log_file = log_dir / f"fundamental_fetch_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
        handlers.append(logging.FileHandler(log_file))

    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=handlers
    )

    return logging.getLogger(__name__)


def extract_symbols_from_trade_logs(trade_logs_folder: Path) -> list:
    """Extract unique symbols from trade log filenames."""
    symbols = set()

    for file_path in trade_logs_folder.glob("*_trades.csv"):
        filename = file_path.stem
        parts = filename.rsplit('_', 2)

        if len(parts) >= 2 and parts[-1] == 'trades':
            symbols.add(parts[-2])

    return sorted(symbols)


def main():
    parser = argparse.ArgumentParser(
        description='Fetch fundamental data from Alpha Vantage',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s logs/AlphaTrendStrategy
  %(prog)s logs/AlphaTrendStrategy --start-year 2015 --end-year 2024
  %(prog)s logs/AlphaTrendStrategy -o analysis_output/fundamentals
  %(prog)s --create-config
        """
    )

    parser.add_argument(
        'trade_logs_folder',
        type=Path,
        nargs='?',
        help='Path to folder containing trade log CSV files'
    )

    parser.add_argument(
        '-o', '--output',
        type=Path,
        help='Output directory for fundamental data files'
    )

    parser.add_argument(
        '--start-year',
        type=int,
        default=2010,
        help='First year to fetch data for (default: 2010)'
    )

    parser.add_argument(
        '--end-year',
        type=int,
        default=datetime.now().year,
        help=f'Last year to fetch data for (default: {datetime.now().year})'
    )

    parser.add_argument(
        '--config',
        type=Path,
        help='Path to Alpha Vantage config file (default: searches standard locations)'
    )

    parser.add_argument(
        '--raw-data',
        type=Path,
        default=Path('raw_data'),
        help='Directory containing raw price CSV files (default: raw_data)'
    )

    parser.add_argument(
        '--symbols',
        type=str,
        nargs='+',
        help='Specific symbols to fetch (overrides trade log extraction)'
    )

    parser.add_argument(
        '--create-config',
        action='store_true',
        help='Create a sample configuration file and exit'
    )

    parser.add_argument(
        '--clear-cache',
        action='store_true',
        help='Clear API response cache before fetching'
    )

    parser.add_argument(
        '--clear-answers',
        action='store_true',
        help='Clear remembered answers before starting'
    )

    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Enable verbose output'
    )

    args = parser.parse_args()

    # Handle --create-config
    if args.create_config:
        create_sample_config()
        return 0

    # Validate arguments
    if not args.trade_logs_folder and not args.symbols:
        parser.error("Either trade_logs_folder or --symbols is required")

    if args.trade_logs_folder and not args.trade_logs_folder.exists():
        parser.error(f"Trade logs folder not found: {args.trade_logs_folder}")

    # Determine output directory
    if args.output:
        output_dir = args.output
    elif args.trade_logs_folder:
        output_dir = args.trade_logs_folder.parent / "analysis_output" / args.trade_logs_folder.name / "fundamental_data"
    else:
        output_dir = Path("analysis_output/fundamental_data")

    log_dir = output_dir / "logs"

    # Setup logging
    logger = setup_logging(args.verbose, log_dir)

    print("=" * 60)
    print("Fundamental Data Fetcher")
    print("=" * 60)

    # Load configuration
    try:
        config = AlphaVantageConfig.load(args.config)
        print(f"API config loaded (rate limit: {config.rate_limit_per_minute}/min)")
    except (FileNotFoundError, ValueError) as e:
        print(f"\nError: {e}")
        print("\nTo create a sample config file, run:")
        print("  python run_fundamental_data_fetch.py --create-config")
        return 1

    # Initialize client
    client = AlphaVantageClient(config)

    if args.clear_cache:
        print("Clearing API cache...")
        client.clear_cache()

    # Initialize interactive handler
    handler = InteractiveHandler(log_dir=log_dir)

    if args.clear_answers:
        print("Clearing remembered answers...")
        handler.clear_memory()

    # Initialize fetcher
    price_data_dir = args.raw_data if args.raw_data.exists() else None
    fetcher = FundamentalDataFetcher(client, handler, price_data_dir)

    # Get symbols to fetch
    if args.symbols:
        symbols = args.symbols
    else:
        symbols = extract_symbols_from_trade_logs(args.trade_logs_folder)

    if not symbols:
        print("No symbols found to process")
        return 1

    print(f"\nSymbols to fetch: {len(symbols)}")
    print(f"Date range: {args.start_year} - {args.end_year}")
    print(f"Output directory: {output_dir}")
    print(f"Log directory: {log_dir}")

    if price_data_dir:
        print(f"Using local price data from: {price_data_dir}")
    else:
        print("Using Alpha Vantage for price data (slower)")

    print()

    # Confirm before starting
    try:
        response = input("Continue? [Y/n]: ").strip().lower()
        if response and response not in ('y', 'yes'):
            print("Aborted by user")
            return 0
    except EOFError:
        pass  # Non-interactive mode

    print()

    # Fetch data
    try:
        results = fetcher.fetch_for_multiple_symbols(
            symbols=symbols,
            start_year=args.start_year,
            end_year=args.end_year,
            output_dir=output_dir
        )
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        results = {}

    # Print summary
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)

    print(f"\nSymbols processed: {len(results)}/{len(symbols)}")
    print(f"Output directory: {output_dir}")

    if results:
        print(f"\nGenerated files:")
        for symbol, path in sorted(results.items()):
            print(f"  {symbol}: {path.name}")

    # Print decision summary
    handler.print_summary()

    # Print cache stats
    cache_stats = client.get_cache_stats()
    print(f"\nAPI Cache: {cache_stats['num_cached_responses']} responses ({cache_stats['total_size_mb']} MB)")

    print("\n" + "=" * 60)
    print("Fetch Complete!")
    print("=" * 60)

    return 0


if __name__ == '__main__':
    sys.exit(main())
